# Generated by Django 5.2 on 2025-04-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDS', '0002_pcapfile_analysis_result_pcapfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_packets', models.IntegerField()),
                ('malicious_count', models.IntegerField()),
                ('normal_count', models.IntegerField()),
                ('malicious_ips', models.JSONField(blank=True, default=list)),
                ('model_details', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pcap_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_report', to='IDS.pcapfile')),
            ],
        ),
    ]
