# Generated by Django 5.2 on 2025-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDS', '0003_analysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcapfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
