# Generated by Django 5.2 on 2025-05-01 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDS', '0005_remove_analysisresult_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcapfile',
            name='progress_status',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcapfile',
            name='analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcapfile',
            name='progress_message',
            field=models.CharField(blank=True, default='File uploaded successfully', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pcapfile',
            name='progress_stage',
            field=models.CharField(choices=[('uploaded', 'File Uploaded'), ('converting', 'Converting PCAP to CSV'), ('preprocessing', 'Preprocessing Data'), ('predicting', 'Running Predictions'), ('saving', 'Saving Results'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='malicious_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='model_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='pcap_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_report', to='IDS.pcapfile'),
        ),
        migrations.AlterField(
            model_name='pcapfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
